Workaround possible bug in rspec-rails
The code introduced in rspec/rspec-rails##1238 blows up with the error:

  NameError:
    undefined method `constant_mutator_for'

when enabling Active Record and using `instance_double``. Changing to
`object_double` works around the problem for now.